name: Build on Ubuntu

on:
  push:
    branches:
      - master

env:
  # Release, Debug, RelWithDebInfo, ...
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        path: src

    - name: Build
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
       cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "Unix Makefiles" -S "${{github.workspace}}/src" -B "${{github.workspace}}/build"
       cmake --build "${{github.workspace}}/build" --config %BUILD_TYPE% -j $(nproc --all)
