name: Build on Windows

on:
  push:
    branches:
      - master

env:
  # Release, Debug, RelWithDebInfo, ...
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        path: src

    - name: Build
      working-directory: ${{github.workspace}}/src
      shell: cmd
      run: |
       cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "Visual Studio 16 2019" -S "${{github.workspace}}/src" -B "${{github.workspace}}/build"
       cmake --build "${{github.workspace}}/build" --config %BUILD_TYPE% -j %NUMBER_OF_PROCESSORS%
